language: go
go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - tip
matrix:
    allow_failures:
        - go: tip
env:
    - TODO_DB_NAME=todo
install:
    - go get github.com/tools/godep
    - godep restore
before_script:
    - psql -c 'create database todo;' -U postgres
    - psql -U postgres todo < db/tables.sql
script:
    - make test
