language: go
go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - tip
matrix:
    allow_failures:
        - go: tip
install:
    - go get github.com/tools/godep
    - godep restore
before_script:
    - git clone http://github.com/mssola/scripts mssola
    - cp db/test.json db/database.json
    - psql -c 'create database todo;' -U postgres
    - ./mssola/db -e test < db/tables.sql
script:
    - godep go test -v ./...
